### ISSUE TITLE
`serverlist.json` Not Found

### ISSUE THREAD

**Issue by BIGBEASTISHANK** [ProtonVPN/proton-vpn-gtk-app#28]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------
I have installed proton-vpn-gtk-app and it was not connecting to vpn, saying auth denied some thing like that, then i uninstalled it completly, removed every file and folder it created. Reinstalled it and it is showing this error

```bash
2024-02-04T02:01:34.907074 | proton.vpn.connection.vpnconnector:168 | INFO | CONN:STATE_CHANGED | Disconnected (initial state)
2024-02-04T02:01:35.107865 | proton.vpn.session.session:92 | ERROR | Error deserializing VPN session.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/proton/vpn/session/servers/fetcher.py", line 107, in load_from_cache
    cache = self._cache_file.load()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/vpn/session/cache.py", line 57, in load
    return CacheFile.from_path(self.file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/vpn/session/cache.py", line 69, in from_path
    with open(file_path, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ishank/.cache/Proton/VPN/serverlist.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/proton/vpn/session/session.py", line 89, in __setstate__
    self._server_list = self._fetcher.load_server_list_from_cache()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/vpn/session/fetcher.py", line 96, in load_server_list_from_cache
    return self._server_list_fetcher.load_from_cache()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/proton/vpn/session/servers/fetcher.py", line 109, in load_from_cache
    raise ServerListDecodeError("Cached server list was not found") from error
proton.vpn.session.exceptions.ServerListDecodeError: Cached server list was not found
```
I tried restarting my pc but nothing worked

**Comment by BIGBEASTISHANK** [comment]
Got solved automaticaly and also found same closed issue #25
