### ISSUE TITLE
AttributeError: 'KeyringBackendLinuxSecretService' object has no attribute 'KEYRING_SERVICE'

### ISSUE THREAD

**Issue by Anonymous941** [ProtonVPN/proton-vpn-gtk-app#44]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------
When executing `protonvpn-app` after updating:
```plain
(protonvpn-app:1227797): Gdk-WARNING **: 14:49:26.033: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
Traceback (most recent call last):
  File "/usr/bin/protonvpn-app", line 33, in <module>
    sys.exit(load_entry_point('proton-vpn-gtk-app==4.3.0', 'console_scripts', 'protonvpn-app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/__main__.py", line 34, in main
    controller = Controller.get(executor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 57, in get
    executor.submit(controller.initialize_vpn_connector).result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 97, in initialize_vpn_connector
    self._connector = await self._api.get_vpn_connector()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 55, in get_vpn_connector
    settings = await self.load_settings()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 65, in load_settings
    if self._session_holder.session.logged_in:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/core/session.py", line 73, in session
    self._session = self._proton_sso.get_default_session(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/sso/sso.py", line 192, in get_default_session
    sessions = self.sessions
               ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/sso/sso.py", line 133, in sessions
    keyring_index = keyring[self.__keyring_index_name()]
                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/keyring/_base.py", line 65, in __getitem__
    return self._get_item(key)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/keyring_linux/secretservice/secretservice_backend.py", line 57, in _get_item
    self.KEYRING_SERVICE,
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'KeyringBackendLinuxSecretService' object has no attribute 'KEYRING_SERVICE'
```

**Comment by calexandru2018** [comment]
Make sure that you've updated both packages, it seems like you didn't update the linux-keyring one

**Comment by Anonymous941** [comment]
For some reason, all attempts to upgrade that package fail (running `apt update && apt upgrade` and `pip3 install proton-keyring-linux==0.0.2` both result in an error), but cloning the source and building manually somehow fixed it

**Comment by Anonymous941** [comment]
Thanks for maintaining this repository!  I'm really excited about the recent bugfixes and features
