### ISSUE TITLE
ProtonVPN Fatal Error on Connect in Ubuntu 23.10 on Raspberry Pi 5

### ISSUE THREAD

**Issue by nstrobl** [ProtonVPN/proton-vpn-gtk-app#46]
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------
OS: Ubuntu 23.10
Hardware: Raspberry Pi 5
Running as a system user
Checked permissions for .cache, correct
All optional features turned off
Reinstall tried
Tried running on newly created user
Stable (4.3.0) and Beta version tried
Different countries/servers tried

ProtonVPN becomes stuck in the 'connecting' state. If the application is closed, it will only open again after a restart.

Relevant logs:

2024-04-27T17:26:06.188771 | proton.vpn.session.session:92 | ERROR | Error deserializing VPN session.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/proton/vpn/session/servers/fetcher.py", line 107, in load_from_cache
    cache = self._cache_file.load()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/session/cache.py", line 57, in load
    return CacheFile.from_path(self.file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/session/cache.py", line 69, in from_path
    with open(file_path, "r", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/seedbox/.cache/Proton/VPN/serverlist.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/proton/vpn/session/session.py", line 89, in __setstate__
    self._server_list = self._fetcher.load_server_list_from_cache()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/session/fetcher.py", line 96, in load_server_list_from_cache
    return self._server_list_fetcher.load_from_cache()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proton/vpn/session/servers/fetcher.py", line 109, in load_from_cache
    raise ServerListDecodeError("Cached server list was not found") from error
proton.vpn.session.exceptions.ServerListDecodeError: Cached server list was not found

**Comment by calexandru2018** [comment]
hey @nstrobl , since we don't haven't tested it on a RPI we can't assure that it'll work. It though was noted by a community member that it worked on Ubuntu 24.04 on a RPI 5. I'll be closing the ticket, but do let me know of the outcome if you ever try it.
