### ISSUE TITLE
Proton-vpn not working on manjaro anymore

### ISSUE THREAD

**Issue by AntouanK** [ProtonVPN/proton-vpn-gtk-app#49]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

Since the latest update, the app is not working on manjaro ( it was working fine until now )

I'm getting a "ModuleNotFoundError" when I try to launch it.

Any idea on what the issue is?

[Complete logs from installing all the packages needed ( `yay` did all of it )](https://gist.github.com/AntouanK/11df9a29b1717f0932c892c6de5c8c03)

```
~ took 54s
❯ protonvpn-app
Traceback (most recent call last):
  File "/usr/bin/protonvpn-app", line 33, in <module>
    sys.exit(load_entry_point('proton-vpn-gtk-app==4.3.0', 'console_scripts', 'protonvpn-app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/protonvpn-app", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/proton/vpn/app/gtk/__init__.py", line 33, in <module>
    from proton.vpn import logging  # pylint: disable=C0413 # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/proton/vpn/logging/__init__.py", line 26, in <module>
    from proton.utils.environment import VPNExecutionEnvironment
ModuleNotFoundError: No module named 'proton.utils'
```

**Comment by AntouanK** [comment]
I found [the solution in the arch wiki](https://aur.archlinux.org/packages/proton-vpn-gtk-app#comment-969741).

run `yay -Rs proton-vpn-gtk-app` to uninstall all the related python packages.
Then `yay -S proton-vpn-gtk-app` again.
That worked for me.
