### ISSUE TITLE
Proton VPN app won't open on openSuse TW

### ISSUE THREAD

**Issue by serial02** [ProtonVPN/proton-vpn-gtk-app#53]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------
Distribution: openSUSE Tumbleweed x86_64
FROM: GNOME 46.1
Kernel: 6.9.1-1-default

When I click on the Proton VPN icon it does not open.
 When I try to open the application through the terminal I receive the following error message:

```
edson@localhost:~> sudo /usr/bin/protonvpn-app
Traceback (most recent call last):
  File "/usr/bin/protonvpn-app", line 33, in <module>
    sys.exit(load_entry_point('proton-vpn-gtk-app==4.2.0', 'console_scripts', 'protonvpn-app')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/protonvpn-app", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/proton/vpn/app/gtk/__main__.py", line 25, in <module>
    from proton.vpn.app.gtk.app import App
  File "/usr/lib/python3.11/site-packages/proton/vpn/app/gtk/app.py", line 28, in <module>
    from proton.vpn.app.gtk.controller import Controller
  File "/usr/lib/python3.11/site-packages/proton/vpn/app/gtk/controller.py", line 29, in <module>
    from proton.vpn.core.session import ClientTypeMetadata
ImportError: cannot import name 'ClientTypeMetadata' from 'proton.vpn.core.session' (/usr/lib/python3.11/site-packages/proton/vpn/core/session/__init__.py)
``` 

This problem has been unresolved for almost a month now.

Is there any temporary solution to this problem?

**Comment by tired-creating-those-usernames** [comment]
very similar on ubuntu based TuxedoOS:
clicking the app GUI only loads for seconds and drops activity. 
CLI:
─>‎ protonvpn-app
Traceback (most recent call last):
  File "/usr/bin/protonvpn-app", line 33, in <module>
    sys.exit(load_entry_point('proton-vpn-gtk-app==4.3.2', 'console_scripts', 'protonvpn-app')())
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/__main__.py", line 34, in main
    controller = Controller.get(executor)
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 59, in get
    executor.submit(controller.initialize_vpn_connector).result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/proton/vpn/app/gtk/controller.py", line 94, in initialize_vpn_connector
    self._connector = await self._api.get_vpn_connector()
  File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 57, in get_vpn_connector
    settings = await self.load_settings()
  File "/usr/lib/python3/dist-packages/proton/vpn/core/api.py", line 68, in load_settings
    user_tier = self._session_holder.session.vpn_account.max_tier
AttributeError: 'NoneType' object has no attribute 'max_tier'

**Comment by calexandru2018** [comment]
Since we don't officially support OpenSUSE i'll be closing this ticket.
