### ISSUE TITLE
NetworkManager PermissionDenied

### ISSUE THREAD

**Issue by Picollus1** [ProtonVPN/proton-vpn-gtk-app#67]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [X] I have searched open and closed issues for duplicates
- [X] This isn't a feature request
- [ ] This is not a report about my app not working as expected

----------------------------------------

Unable to connect any country as i get the following error in log : 

Proton.vpn.app.gtk.widgets.main.exception_handler:175 | CRITICAL | APP:CRASH | Unexpected error.
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/proton/vpn/killswitch/backend/linux/networkmanager/nmclient.py", line 332, in _on_property_set
    if not nm_client or not res or not nm_client.dbus_set_property_finish(res):

gi.repository.GLib.GError: nm-manager-error-quark: GDBus.Error:org.freedesktop.NetworkManager.PermissionDenied: Not authorized to perform this operation (1)

I am running Mint Linux.

I tried to allow everything in /usr/share/dbus-1/system.d/org.freedesktop.NetworkManager.conf without any success. Same error occur.

**Comment by 0xl30** [comment]
> Traceback (most recent call last): File "/app/lib/python3.11/site-packages/proton/vpn/killswitch/backend/linux/networkmanager/nmclient.py", line 332, in _on_property_set if not nm_client or not res or not nm_client.dbus_set_property_finish(res):
> 
> gi.repository.GLib.GError: nm-manager-error-quark: GDBus.Error:org.freedesktop.NetworkManager.PermissionDenied: Not authorized to perform this operation (1)

i think your problem is polkit permission.

**Comment by SIMULATAN** [comment]
Since you are using NetworkManager, this solution from the Arch Wiki may help: https://wiki.archlinux.org/title/ProtonVPN#Official_client_will_not_connect

In short, on Arch Linux, install `network-manager-applet`. On Mint, I couldn't find the package, it may be included in the main NetworkManager one.
In any case, run `nohup nm-applet > /dev/null &` to launch the applet. Restart the ProtonVPN app for good measure and try to reconnect.

**Comment by mainrs** [comment]
Does anybody know how to get this to work without nm-applet? Some desktop environments ship their own WiFi applet. For those I had to disable the builtin one and use nm-applet.

I could not find any references in the code that relies on the applet to run. Maybe I am just looking at the wrong code paths though.

**Comment by MiSalocin** [comment]
I got it working on arch only installing `NetworkManager` and running `sudo NetworkManager`
